# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa56bead49a47d5d4fc409940e8ef6516837b7de681ee0cf00a57908c2e127b5a08f648c69122996f96a32734ec07195f97c4e1dc089536ece5f9636bceca95f

test:
  secret_key_base: a7b5d1ebc42ff5fa10591eaa4f1a0dae29e871a8749af6194efc85d318497cf66a0f8430fa67ef9aa0090e32ddea38e78b22bfb44d1352f39c5ee94f6e48cbac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
